# Site settings
title: Skooris
email: Skooris@mouge.wang
description: Skooris's awesome CV intro website.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://skooris.github.io/" # the base hostname & protocol for your site
twitter_username: skooris
github_username:  skooris

# Build settings
markdown: kramdown
